const  TODO = {
    ADD_ITEM : 'ADDITEM',
    DELETE_ITEM :'DELTEITEM',
    UPDATE_ITEM : 'UPDATEITEM',
    LINE_ITEM :'LINE_ITEM',
    SHOW_ALL :'SHOWALL',
    SHOW_ACTIVE:'SHOWACTIVE',
    SHOW_COMPLETED :'SHOWCOMPLETED',
    VISIBILITY :'VISIBILITY',
    CLEAR_COMPLETED :'CLEARCOMPLETED'
}

export default TODO;